### ISSUE TITLE
4k will not encode on version 6.44

### ISSUE THREAD

**Issue by sdugoten** [RandomEngy/VidCoder#942]
### Problem Description

![image](https://user-images.githubusercontent.com/7108552/145839326-722f068a-8508-4408-b973-7802ee25b261.png)

 
![image](https://user-images.githubusercontent.com/7108552/145839268-d0251fac-a720-443a-a6ac-73ec260a456f.png)

4K encode will not work on version 6.44.  It will fail and throw the following error.  I have tried H265 and H264 and both failed.  Also tried on H265 (NVec) and that doesn't work as well.  However, same setting works in Handbrake

### What version of VidCoder are you running?

6.44

### Encode Log

```text
# VidCoder 6.44
# Starting job 1/1
#   Source path: G:\Migration\house_pic\SE3GoproDec5\orig\GH010033.MP4
#   Destination path: G:\Gh010033.mp4
#   Title: 1
#   Range: All
#   Preset: 4KH265
# Worker ready: Pipe 'VidCoderWorker.b2d9a186-c3fd-4ba3-a257-2d91b4f8d74e' is open
# Connecting to process 64912 on pipe VidCoderWorker.b2d9a186-c3fd-4ba3-a257-2d91b4f8d74e
[15:22:30] CPU: AMD Ryzen 9 3950X 16-Core Processor
[15:22:30]  - logical processor count: 32
[15:22:30] Intel Quick Sync Video support: no
[15:22:30] hb_scan: path=G:\Migration\house_pic\SE3GoproDec5\orig\GH010033.MP4, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:333: failed opening UDF image G:\Migration\house_pic\SE3GoproDec5\orig\GH010033.MP4
src/libbluray/disc/disc.c:437: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:437: error opening file BDMV\BACKUP\index.bdmv
src/libbluray/bluray.c:2646: nav_get_title_list(G:\Migration\house_pic\SE3GoproDec5\orig\GH010033.MP4\) failed
[15:22:30] bd: not a bd - trying as a stream/file instead
libdvdread: DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
[15:22:30] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'G:\Migration\house_pic\SE3GoproDec5\orig\GH010033.MP4':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    creation_time   : 2021-12-11T15:23:29.000000Z
    firmware        : HD9.01.01.60.00
  Duration: 00:02:55.02, start: 0.000000, bitrate: 100257 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 100007 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2021-12-11T15:23:29.000000Z
      handler_name    : GoPro AVC
      vendor_id       : [0][0][0][0]
      encoder         : GoPro AVC encoder
      timecode        : 15:23:29:18
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2021-12-11T15:23:29.000000Z
      handler_name    : GoPro AAC
      vendor_id       : [0][0][0][0]
      timecode        : 15:23:29:18
  Stream #0:2(eng): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2021-12-11T15:23:29.000000Z
      handler_name    : GoPro TCD
      timecode        : 15:23:29:18
  Stream #0:3(eng): Data: bin_data (gpmd / 0x646D7067), 50 kb/s (default)
    Metadata:
      creation_time   : 2021-12-11T15:23:29.000000Z
      handler_name    : GoPro MET
  Stream #0:4(eng): Data: none (fdsc / 0x63736466), 9 kb/s (default)
    Metadata:
      creation_time   : 2021-12-11T15:23:29.000000Z
      handler_name    : GoPro SOS
[15:22:30] scan: decoding previews for title 1
[15:22:30] scan: audio 0x1: aac, rate=48000Hz, bitrate=189344 English (AAC LC) (2.0 ch) (189 kbps)
[15:22:32] scan: 10 previews, 3840x2160, 25.000 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1, color profile: 1-1-1
[15:22:32] libhb: scan thread found 1 valid title(s)
[15:22:32] Starting work at: Mon Dec 13 15:22:32 2021
[15:22:32] 1 job(s) to process
[15:22:32] json job:
{
  "Audio": {
    "AudioList": [
      {
        "Bitrate": 128,
        "DRC": 0,
        "Encoder": "av_aac",
        "Gain": 0,
        "Mixdown": 4,
        "NormalizeMixLevel": false,
        "Samplerate": 0,
        "Track": 0,
        "DitherMethod": 0
      },
      {
        "DRC": 0,
        "Encoder": "copy:ac3",
        "Gain": 0,
        "Mixdown": 0,
        "NormalizeMixLevel": false,
        "Samplerate": 0,
        "Track": 0,
        "DitherMethod": 0
      }
    ],
    "CopyMask": [
      "copy:aac",
      "copy:ac3",
      "copy:eac3",
      "copy:truehd",
      "copy:dts",
      "copy:dtshd",
      "copy:mp2",
      "copy:mp3",
      "copy:flac"
    ]
  },
  "Destination": {
    "ChapterList": [],
    "ChapterMarkers": false,
    "AlignAVStart": false,
    "File": "G:\\Gh010033.part.mp4",
    "Mp4Options": {
      "IpodAtom": false,
      "Mp4Optimize": false
    },
    "Mux": "av_mp4"
  },
  "Filters": {
    "FilterList": [
      {
        "ID": 4,
        "Settings": {
          "mode": "7"
        }
      },
      {
        "ID": 3,
        "Settings": {
          "block-height": "16",
          "block-thresh": "40",
          "block-width": "16",
          "filter-mode": "2",
          "mode": "3",
          "motion-thresh": "1",
          "spatial-metric": "2",
          "spatial-thresh": "1"
        }
      },
      {
        "ID": 13,
        "Settings": {
          "crop-bottom": "0",
          "crop-left": "0",
          "crop-right": "0",
          "crop-top": "0",
          "height": "2160",
          "width": "3840"
        }
      }
    ]
  },
  "PAR": {
    "Num": 1,
    "Den": 1
  },
  "Metadata": {},
  "SequenceID": 0,
  "Source": {
    "Angle": 1,
    "Range": {
      "Type": "chapter",
      "Start": 1,
      "End": 1
    },
    "Title": 1,
    "Path": "G:\\Migration\\house_pic\\SE3GoproDec5\\orig\\GH010033.MP4"
  },
  "Subtitle": {
    "Search": {
      "Burn": false,
      "Default": false,
      "Enable": true,
      "Forced": true
    },
    "SubtitleList": []
  },
  "Video": {
    "Encoder": "x265",
    "Level": "4.0",
    "TwoPass": false,
    "Turbo": false,
    "ColorMatrixCode": 0,
    "Options": "",
    "Preset": "slow",
    "Profile": "auto",
    "Quality": 22,
    "QSV": {
      "Decode": false
    }
  }
}
[15:22:32] Skipping subtitle scan.  No suitable subtitle tracks.
[15:22:32] Starting Task: Encoding Pass
[15:22:32] Skipping crop/scale filter
[15:22:32] Passthru requested and input codec is not the same as output codec for track 2, dropping track
[15:22:32] work: track 1, dithering not supported by codec
[15:22:32] job configuration:
[15:22:32]  * source
[15:22:32]    + G:\Migration\house_pic\SE3GoproDec5\orig\GH010033.MP4
[15:22:32]    + title 1, chapter(s) 1 to 1
[15:22:32]    + container: mov,mp4,m4a,3gp,3g2,mj2
[15:22:32]    + data rate: 100257 kbps
[15:22:32]  * destination
[15:22:32]    + G:\Gh010033.part.mp4
[15:22:32]    + container: MPEG-4 (libavformat)
[15:22:32]  * video track
[15:22:32]    + decoder: h264 8-bit (yuv420p)
[15:22:32]      + bitrate 100007 kbps
[15:22:32]    + filters
[15:22:32]      + Comb Detect (mode=3:spatial-metric=2:motion-thresh=1:spatial-thresh=1:filter-mode=2:block-thresh=40:block-width=16:block-height=16)
[15:22:32]      + Decomb (mode=39)
[15:22:32]    + Output geometry
[15:22:32]      + storage dimensions: 3840 x 2160
[15:22:32]      + pixel aspect ratio: 1 : 1
[15:22:32]      + display dimensions: 3840 x 2160
[15:22:32]    + encoder: H.265 (libx265)
[15:22:32]      + preset:  slow
[15:22:32]      + profile: auto
[15:22:32]      + level:   4.0
[15:22:32]      + quality: 22.00 (RF)
[15:22:32]      + color profile: 1-1-1
[15:22:32]  * audio track 1
[15:22:32]    + decoder: English (AAC LC) (2.0 ch) (189 kbps) (track 1, id 0x1)
[15:22:32]      + bitrate: 189 kbps, samplerate: 48000 Hz
[15:22:32]    + mixdown: Stereo
[15:22:32]    + encoder: AAC (libavcodec)
[15:22:32]      + bitrate: 128 kbps, samplerate: 48000 Hz
[15:22:32] sync: expecting 4375 video frames
x265 [info]: HEVC encoder version 3.5+1-f0c1022b6
x265 [info]: build info [Windows][clang 12.0.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [error]: picture dimensions are out of range for specified level
encx265: x265_encoder_open failed.
Failure to initialise thread 'H.265/HEVC encoder (libx265)'
[15:22:32] comb detect: heavy 0 | light 0 | uncombed 0 | total 0
[15:22:32] decomb: deinterlaced 0 | blended 0 | unfiltered 0 | total 0
[15:22:32] aac-decoder done: 0 frames, 0 decoder errors
[15:22:32] h264-decoder done: 0 frames, 0 decoder errors
[15:22:32] sync: got 0 frames, 4375 expected
[15:22:33] Finished work at: Mon Dec 13 15:22:33 2021
[15:22:33] libhb: work result = 3
ERROR: Encode failed with code ErrorInit
# Job completed (Elapsed Time: 3s)
```

**Comment by RandomEngy** [comment]
Have you tried setting "Level" to "Auto"?

**Comment by sdugoten** [comment]
ok, setting to auto does correct the problem.  thx
