### ISSUE TITLE
An error occurred while scanning.

### ISSUE THREAD

**Issue by stevenbrigita** [RandomEngy/VidCoder#476]
I have the error "an error occurred while scanning" when I try to import a mp4 into VidCoder 4.29. I have always had the same error with beta 4.xx, but works perfectly in all 3.xx versions!? It is NOT an encrypted or protected file so I am unsure why it doesn't work. I made a short clip I can send in for testing if that would help. 

Thank you
![sshot-11](https://user-images.githubusercontent.com/46755256/51264499-a409e480-1984-11e9-9f82-bf6178c2a4c5.jpg)

**Comment by stevenbrigita** [comment]
Thank you for your response.

I did try it in Handbrake after I posted the bug. It did not work, but 
don't understand why it works in VidCoder 3.16 no problem. Are you using 
an older version of Handbrake??

This is the result from Handbrake if you are interested. I guess there 
is a problem with the header in the mp4? I opened it in AVIdemux and 
simply saved it again as mp4 and now works no problem in VidCoder?!?

Keep up the great work. If you can let me know which version of 
handbrake you are using in 3.16 si I can let the Handbrake team know the 
files works in older version.

THANK YOU!!


HandBrake 1.2.0 (2018121700)

OS: Microsoft Windows NT 10.0.17134.0

Ram: 16325 MB,

GPU Information:

NVIDIA GeForce GTX 970 - 24.21.13.9907

Screen: 3840x2160

Temp Dir: C:\Users\Steven\AppData\Local\Temp\

Install Dir: D:\Desktop\HandBrake 1.2.0

Data Dir: C:\Users\Steven\AppData\Roaming\HandBrake

-------------------------------------------

[12:03:41] hb_init: starting libhb thread

# Starting Scan ...

[12:03:41] CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

[12:03:41]- Intel microarchitecture Haswell

[12:03:41]- logical processor count: 8

[12:03:41] Intel Quick Sync Video support: no

[12:03:41] hb_scan: path=D:\Desktop\Rec_401.mp4, title_index=0

udfread ERROR: ECMA 167 Volume Recognition failed

src/libbluray/disc/disc.c:323: failed opening UDF image 
D:\Desktop\Rec_401.mp4

src/libbluray/disc/disc.c:424: error opening file BDMV\index.bdmv

src/libbluray/disc/disc.c:424: error opening file BDMV\BACKUP\index.bdmv

[12:03:41] bd: not a bd - trying as a stream/file instead

libdvdnav: Using dvdnav version 6.0.0

libdvdread: Encrypted DVD support unavailable.

libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed

libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed

libdvdread: Can't open file VIDEO_TS.IFO.

libdvdnav: vm: failed to read VIDEO_TS.IFO

[12:03:41] dvd: not a dvd - trying as a stream/file instead

[mov,mp4,m4a,3gp,3g2,mj2 @ 000002b1fddb0c00] error reading header

[12:03:41] hb_stream_open: open D:\Desktop\Rec_401.mp4 failed

[12:03:41] scan: unrecognized file type

[12:03:41] libhb: scan thread found 0 valid title(s)

# Processing Scan Information ...

# Scan Finished ...

**Comment by RandomEngy** [comment]
You can check the HandBrake version in Help -> About. VC 3.16 used HandBrake 1.1.2.
